### ISSUE TITLE
[Feature] Routine List API

### ISSUE THREAD

**Issue by ckwogus37** [Programmers-Coach-Coach/Coach-Coach-server#13]
## 어떤 기능인가요?

> 루틴 목록을 조회하는 기능을 구현합니다.

## 작업 상세 내용

- [x] 루틴 목록 조회 API 구현

**Comment by habbiness** [comment]
앗 routineAPI 한꺼번에 하지말고 세부 API로 나눠서 이슈 생성하시고 작업하시는 게 어떨까요??? 아무래도 squash and merge 방법이 커밋들이 다 사라지다보니 최대한 나눠서 하시는 게 좋을 것 같아요! (ex: 루틴 목록 조회 API 구현 후 루틴 개별 조회 API 구현 등등)...
