### ISSUE TITLE
[Feature] Modify Category API

### ISSUE THREAD

**Issue by ckwogus37** [Programmers-Coach-Coach/Coach-Coach-server#211]
## 어떤 기능인가요?

> 카테고리의 정보를 수정하는 API 구현

## 작업 상세 내용

- [ ] 카테고리 수정 기능
- [ ] 일반회원 자신이 만든 / 코치가 회원에게 만들어준 루틴인지 검증
- [ ] 카테고리 이름값 검증

**Comment by hanbirang** [comment]
왜 카테고리 수정 api에 대한 이슈가  두 개인가요?
