### ISSUE TITLE
[Refactor] Refactor Add Coach Info API to Save isCoach

### ISSUE THREAD

**Issue by jeeehdev** [Programmers-Coach-Coach/Coach-Coach-server#254]
## 어떤 기능인가요?

> 코치 정보 등록 시 isCoach값 true 값으로 변경

## 작업 상세 내용

- [ ] coachService 코치 정보 등록 시 isCoach값 true 값으로 변경
- [ ] userService `getLoggedInUserAuthStatus` userReporitory의 isCoach로 변경

## 참고할만한 자료(선택)

**Comment by habbiness** [comment]
이거 userRepository없이 바로! user 객체에서 isCoach값가져오시면 돼요! 대신 entity도 수정하셔야될거예요... 그와 관련된 테스트 코드에도...

**Comment by jeeehdev** [comment]
아 네네 바로 가져오는걸로 했습니다!
